image: docker.flyingflip.com/probo/alpine:php8.1
assets:
  - .env

steps:
  - name: Load variables.
    command: 'source $ASSET_DIR/.env'

  - name: Install Drupal 9 Files From Drupal
    plugin: Script
    script: |
      rm -rf /var/www/html
      cd $SRC_DIR
      composer create-project drupal/recommended-project docroot
      cd /src/docroot
      composer require drush/drush:^11 drupal/admin_toolbar
      chmod -R 777 /src/docroot/web/sites/default

  - name: Run the Drupal 9 Site Installation - Ubuntu
    plugin: Script
    script: |
      cd /src/docroot
      drush si -y --account-name=admin --account-mail=mrbagnall@icloud.com --site-mail=mrbagnall@icloud.com --account-pass=password12345
      drush pm:enable -y admin_toolbar
      chmod 755 /src/docroot/web/sites/default/settings.php

  - name: Set Up Configuration for Drupal 9
    plugin: Drupal
    drupalVersion: 9
    subDirectory: docroot/web

  - name: Install Arlo Module
    plugin: Script
    script: |
      cd /src/docroot/web/modules
      mkdir drupal
      cd drupal
      rsync -av --progress /src /src/docroot/web/modules/drupal --exclude docroot
      cd /src/docroot/web/modules/drupal
      mv src arlo
      drush cr -y
      drush pm:enable -y arlo
