<?php

/**
 * @file
 * Contains arlo.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function arlo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the arlo module.
    case 'help.page.arlo':
      $output = '<h4>' . t('Overview') . '</h4>';
      return $output;
      break;
    default:
      break;
  }
}

/**
 * Implements hook_theme().
 */
function arlo_theme($existing, $type, $theme, $path) {
  $data['arlo_calendar'] = [
    'variables' => [
      'platform_id' => NULL,
    ],
    'template' => 'arlo-calendar'
  ];

  $data['arlo_search_1'] = [
    'variables' => [
      'platform_id' => NULL,
    ],
    'template' => 'arlo-search-1'
  ];

  $data['arlo_search_2'] = [
    'variables' => [
      'platform_id' => NULL,
    ],
    'template' => 'arlo-search-2'
  ];
  
  for ($i = 1; $i <= 6; $i++) {
    $data['arlo_events_' . $i]['variables'] = [
      'platform_id' => NULL,
      'show_load_more' => NULL,
      'load_more_text' => NULL,
      'dev_mode' => NULL,
      'locations' => NULL,
      'tag' => NULL,
      'template_category_id' => NULL,
      'event_ids' => NULL,
      'template_id' => NULL,
      'max_count' => NULL,
    ];
    $data['arlo_events_' . $i]['template'] = 'arlo-events-' . $i;
  }

  /**
   * Pull in any templates configured in custom hooks.
   */
  $options = [];
  $hook = 'custom_event_templates';
  \Drupal::moduleHandler()->invokeAllWith($hook, function (callable $hook, string $module) use (&$options) {
    $options = $hook();
  });

  foreach ($options as $key => $result) {
    $data['arlo_events_' . $key]['variables'] = [
      'platform_id' => NULL,
      'show_load_more' => NULL,
      'load_more_text' => NULL,
      'dev_mode' => NULL,
      'locations' => NULL,
      'tag' => NULL,
      'template_category_id' => NULL,
      'event_ids' => NULL,
      'template_id' => NULL,
      'max_count' => NULL,
    ];
    $data['arlo_events_' . $key]['template'] = 'arlo-events-' . $key;
  }
  return $data;
}

/**
 * Implements hook_page_attachments().
 */
function arlo_page_attachments(&$variables) {
  $variables['#attached']['library'][] = 'arlo/arlo-calendar';
}

/**
 * Implements hook_custom_event_templates().
 */
// function arlo_custom_event_templates() {
//   return [
//     'test_machine_name' => 'Test Machine Name',
//   ];
// }